/**
 * 设备目录 — 所有子系统的设备定义数组
 *
 * 每个子系统独立常量，由 device-catalog.ts 合并为 DEVICE_CATALOG。
 */

import type { DeviceDefinition } from './types'

// ═══════════════════════════════════════════════════════════════
// 灯光子系统
// ═══════════════════════════════════════════════════════════════

export const LIGHTING_FIXTURES: DeviceDefinition[] = [
  {
    catalogId: 'LIGHT-DOWNLIGHT',
    name: '智能筒灯',
    description: '嵌入式筒灯，点光源',
    type: 'light',
    subtype: 'downlight',
    color: '#d4a853',
    defaultH: 2.7,
    size: [0.085, 0.055, 0.085],
    subsystem: 'lighting',
    mountType: 'ceiling',
    lightType: 'point',
    price: 680,
  },
  {
    // 灯带的"统一入口"——目录里只显示这一条。
    // 画完后用右侧面板的"发光朝向"切换 omni / down / up / wall（对应原本的
    // LIGHT-STRIP / -SKIRTING / -COVE / -WASH-WALL），不需要重新画。
    catalogId: 'LIGHT-STRIP',
    name: '灯带',
    description: '线性 LED 灯带，画完后可切换发光朝向（向下/向上/洗墙/全向）',
    type: 'light',
    subtype: 'strip',
    color: '#d4a853',
    defaultH: 2.6,
    size: [0.5, 0.005, 0.01],
    subsystem: 'lighting',
    mountType: 'hidden',
    lightType: 'line',
    price: 280,
  },
  // ── 以下 3 条是【向后兼容】定义 ──
  // 老项目的设备节点 productId 还可能是这些 catalogId，加载时仍要 resolve 到
  // DeviceDefinition 拿 size / mountType。它们不进 catalog 选择器（hiddenFromCatalog）。
  // 新项目都用 LIGHT-STRIP + emissionDirection 表达。
  {
    catalogId: 'LIGHT-STRIP-WASH-WALL',
    name: '洗墙灯',
    description: '（旧版）已合并到"灯带 / 洗墙"模式',
    type: 'light',
    subtype: 'strip-wash-wall',
    color: '#d4a853',
    defaultH: 0.05,
    size: [0.5, 0.05, 0.05],
    subsystem: 'lighting',
    mountType: 'hidden',
    lightType: 'line',
    price: 480,
    hiddenFromCatalog: true,
  },
  {
    catalogId: 'LIGHT-STRIP-COVE',
    name: '回形灯槽',
    description: '（旧版）已合并到"灯带 / 向上"模式',
    type: 'light',
    subtype: 'strip-cove',
    color: '#d4a853',
    defaultH: 2.55,
    size: [0.5, 0.02, 0.03],
    subsystem: 'lighting',
    mountType: 'hidden',
    lightType: 'line',
    price: 360,
    hiddenFromCatalog: true,
  },
  {
    catalogId: 'LIGHT-STRIP-SKIRTING',
    name: '地脚线灯',
    description: '（旧版）已合并到"灯带 / 向下"模式',
    type: 'light',
    subtype: 'strip-skirting',
    color: '#d4a853',
    defaultH: 0.05,
    size: [0.5, 0.01, 0.01],
    subsystem: 'lighting',
    mountType: 'hidden',
    lightType: 'line',
    price: 300,
    hiddenFromCatalog: true,
  },
  {
    catalogId: 'LIGHT-PENDANT',
    name: '吊灯',
    description: '悬挂式吊灯',
    type: 'light',
    subtype: 'pendant',
    color: '#d4a853',
    defaultH: 2.2,
    size: [0.25, 0.4, 0.25],
    subsystem: 'lighting',
    mountType: 'ceiling_suspended',
    lightType: 'physical',
    price: 1200,
  },
  {
    catalogId: 'LIGHT-WALL',
    name: '壁灯',
    description: '壁挂式壁灯',
    type: 'light',
    subtype: 'wall-light',
    color: '#d4a853',
    defaultH: 1.8,
    size: [0.12, 0.18, 0.1],
    subsystem: 'lighting',
    mountType: 'wall',
    lightType: 'physical',
    price: 550,
  },
]

// ═══════════════════════════════════════════════════════════════
// 面板子系统
// ═══════════════════════════════════════════════════════════════

export const LIGHTING_CONTROLS: DeviceDefinition[] = [
  {
    catalogId: 'PANEL-SWITCH-1KEY',
    name: '单路开关',
    description: '单键智能开关面板',
    type: 'panel',
    subtype: 'switch-1key',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.008, 0.086],
    subsystem: 'panel',
    mountType: 'wall_switch',
    buttonCount: 1,
    controlType: 'switch',
    price: 380,
  },
  {
    catalogId: 'PANEL-SWITCH-2KEY',
    name: '双路开关',
    description: '双键智能开关面板',
    type: 'panel',
    subtype: 'switch-2key',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.008, 0.086],
    subsystem: 'panel',
    mountType: 'wall_switch',
    buttonCount: 2,
    controlType: 'switch',
    price: 480,
  },
  {
    catalogId: 'PANEL-SWITCH-3KEY',
    name: '三路开关',
    description: '三键智能开关面板',
    type: 'panel',
    subtype: 'switch-3key',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.008, 0.086],
    subsystem: 'panel',
    mountType: 'wall_switch',
    buttonCount: 3,
    controlType: 'switch',
    price: 580,
  },
  {
    catalogId: 'PANEL-DIMMER-KNOB',
    name: '调光旋钮',
    description: '旋钮式调光面板',
    type: 'panel',
    subtype: 'dimmer-knob',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.012, 0.086],
    subsystem: 'panel',
    mountType: 'wall_switch',
    controlType: 'dimmer',
    price: 680,
  },
  {
    catalogId: 'PANEL-SCENE-4KEY',
    name: '四键场景面板',
    description: '四键场景控制面板',
    type: 'panel',
    subtype: 'scene-4key',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.008, 0.086],
    subsystem: 'panel',
    mountType: 'wall_switch',
    buttonCount: 4,
    controlType: 'scene',
    price: 880,
  },
  {
    catalogId: 'PANEL-SCENE-6KEY',
    name: '六键场景面板',
    description: '六键场景控制面板',
    type: 'panel',
    subtype: 'scene-6key',
    color: '#94A3B8',
    defaultH: 1.35,
    size: [0.086, 0.008, 0.146],
    subsystem: 'panel',
    mountType: 'wall_switch',
    buttonCount: 6,
    controlType: 'scene',
    price: 1200,
  },
]

// ═══════════════════════════════════════════════════════════════
// 暖通子系统
// ═══════════════════════════════════════════════════════════════

export const HVAC_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'HVAC-THERMOSTAT',
    name: '温控面板',
    description: '暖通温度控制面板',
    type: 'panel',
    subtype: 'thermostat',
    color: '#9b7bea',
    defaultH: 1.35,
    size: [0.086, 0.012, 0.086],
    subsystem: 'hvac',
    mountType: 'wall_switch',
    hasScreen: true,
    controlType: 'thermostat',
    price: 1800,
  },
  {
    catalogId: 'HVAC-VENT-4WAY',
    name: '四向出风口',
    description: '中央空调四向出风口',
    type: 'equipment',
    subtype: 'vent-4way',
    color: '#E0E0E0',
    defaultH: 2.7,
    size: [0.3, 0.05, 0.3],
    subsystem: 'hvac',
    mountType: 'ceiling',
    price: 600,
  },
  {
    catalogId: 'HVAC-AC-WALL',
    name: '壁挂空调',
    description: '壁挂式空调室内机（冷暖双模）',
    type: 'equipment',
    subtype: 'ac-wall',
    color: '#9b7bea',
    defaultH: 2.3,
    size: [1.00, 0.30, 0.22],
    subsystem: 'hvac',
    mountType: 'wall',
    price: 4500,
  },
]

// ═══════════════════════════════════════════════════════════════
// 窗帘子系统
// ═══════════════════════════════════════════════════════════════

export const CURTAIN_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'CURTAIN-SIDE-OPEN',
    name: '对开窗帘',
    description: '经典左右对开帘，适配任意窗户宽度',
    type: 'motor',
    subtype: 'curtain-side-open',
    color: '#3dd9b6',
    defaultH: 2.5,
    size: [2.4, 2.2, 0.10],
    subsystem: 'curtain',
    mountType: 'wall',
    requiresOpening: 'window',
    price: 1200,
  },
  {
    catalogId: 'CURTAIN-ROLLER',
    name: '卷帘',
    description: '简洁卷帘，从顶部展开到底',
    type: 'motor',
    subtype: 'curtain-roller',
    color: '#3dd9b6',
    defaultH: 2.5,
    size: [1.8, 2.0, 0.10],
    subsystem: 'curtain',
    mountType: 'wall',
    requiresOpening: 'window',
    price: 800,
  },
  {
    catalogId: 'CURTAIN-VENETIAN',
    name: '百叶窗',
    description: '横向叶片升降 + 角度可调',
    type: 'motor',
    subtype: 'curtain-venetian',
    color: '#3dd9b6',
    defaultH: 2.5,
    size: [1.5, 1.8, 0.04],
    subsystem: 'curtain',
    mountType: 'wall',
    requiresOpening: 'window',
    price: 900,
  },
  {
    catalogId: 'CURTAIN-ROMAN',
    name: '罗马帘',
    description: '分段折叠罗马帘',
    type: 'motor',
    subtype: 'curtain-roman',
    color: '#3dd9b6',
    defaultH: 2.5,
    size: [1.8, 2.0, 0.10],
    subsystem: 'curtain',
    mountType: 'wall',
    requiresOpening: 'window',
    price: 1500,
  },
]

// ═══════════════════════════════════════════════════════════════
// 影音子系统
// ═══════════════════════════════════════════════════════════════

export const AV_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'AV-SMART-SPEAKER',
    name: '智能音箱',
    description: '桌面智能语音音箱（HomePod 类）',
    type: 'equipment',
    subtype: 'smart-speaker',
    color: '#5ba0f5',
    defaultH: 0.12,
    size: [0.14, 0.17, 0.14],
    subsystem: 'av',
    mountType: 'floor',
    price: 1999,
  },
]

// ═══════════════════════════════════════════════════════════════
// 安防子系统
// ═══════════════════════════════════════════════════════════════

export const SECURITY_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'SECURITY-DOOR-LOCK',
    name: '智能门锁',
    description: '智能电子门锁',
    type: 'lock',
    subtype: 'door-lock',
    color: '#FFD700',
    defaultH: 1.0,
    size: [0.07, 0.18, 0.06],
    subsystem: 'security',
    mountType: 'door',
    price: 2800,
  },
  {
    catalogId: 'SECURITY-PIR',
    name: '人体感应器',
    description: '吸顶式人体红外感应',
    type: 'sensor',
    subtype: 'pir',
    color: '#4ade80',
    defaultH: 2.7,
    size: [0.085, 0.045, 0.085],
    subsystem: 'sensor',
    mountType: 'ceiling',
    coverageRadius: 5,
    price: 320,
  },
  {
    catalogId: 'SECURITY-CAMERA-DOME',
    name: '半球摄像头',
    description: '吸顶式半球监控',
    type: 'sensor',
    subtype: 'dome',
    color: '#f59e0b',
    defaultH: 2.7,
    size: [0.12, 0.08, 0.12],
    subsystem: 'security',
    mountType: 'ceiling',
    price: 1500,
  },
  {
    catalogId: 'SECURITY-CAMERA-BULLET',
    name: '枪机摄像头',
    description: '壁挂式枪机监控',
    type: 'sensor',
    subtype: 'camera-bullet',
    color: '#f59e0b',
    defaultH: 2.4,
    size: [0.16, 0.08, 0.08],
    subsystem: 'security',
    mountType: 'wall',
    price: 1680,
  },
  {
    catalogId: 'SECURITY-SMOKE',
    name: '烟感报警器',
    description: '吸顶式烟雾探测',
    type: 'sensor',
    subtype: 'smoke',
    color: '#4ade80',
    defaultH: 2.7,
    size: [0.11, 0.04, 0.11],
    subsystem: 'sensor',
    mountType: 'ceiling',
    price: 280,
  },
]

// ═══════════════════════════════════════════════════════════════
// 网络子系统
// ═══════════════════════════════════════════════════════════════

export const NETWORK_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'NETWORK-AP-CEILING',
    name: '吸顶AP',
    description: '吸顶式无线AP',
    type: 'ap',
    subtype: 'ceiling',
    color: '#60a5fa',
    defaultH: 2.7,
    size: [0.2, 0.04, 0.2],
    subsystem: 'network',
    mountType: 'ceiling',
    coverageRadius: 10,
    price: 1200,
  },
  {
    catalogId: 'NETWORK-AP-WALL',
    name: '面板AP',
    description: '86型面板无线AP',
    type: 'ap',
    subtype: 'wall',
    color: '#60a5fa',
    defaultH: 2.4,
    size: [0.086, 0.03, 0.086],
    subsystem: 'network',
    mountType: 'wall_switch',
    coverageRadius: 8,
    price: 800,
  },
  {
    catalogId: 'NETWORK-ROUTER',
    name: '路由器',
    description: '家用 / 商用千兆路由器',
    type: 'gateway',
    subtype: 'router',
    color: '#60a5fa',
    defaultH: 0.1,
    size: [0.32, 0.05, 0.22],
    subsystem: 'network',
    mountType: 'floor',
    price: 800,
  },
  {
    catalogId: 'NETWORK-SWITCH',
    name: '交换机',
    description: '8 口 / 16 口千兆以太网交换机',
    type: 'equipment',
    subtype: 'switch-network',
    color: '#60a5fa',
    defaultH: 0.1,
    size: [0.28, 0.04, 0.18],
    subsystem: 'network',
    mountType: 'floor',
    price: 600,
  },
  {
    catalogId: 'NETWORK-CABINET-WALL',
    name: '弱电箱',
    description: '墙面嵌入 / 明装家用弱电箱',
    type: 'equipment',
    subtype: 'cabinet-wall',
    color: '#e5e7eb',
    defaultH: 1.2,
    size: [0.31, 0.74, 0.21],
    subsystem: 'network',
    mountType: 'wall',
    price: 500,
  },
  {
    catalogId: 'NETWORK-CABINET-FLOOR',
    name: '落地机柜',
    description: '18U / 22U 标准机柜',
    type: 'equipment',
    subtype: 'cabinet-floor',
    color: '#e5e7eb',
    defaultH: 0,
    size: [0.60, 1.80, 0.60],
    subsystem: 'network',
    mountType: 'floor',
    price: 3500,
  },
]

// ═══════════════════════════════════════════════════════════════
// 架构子系统（网关 / 主机）
// ═══════════════════════════════════════════════════════════════

export const INFRA_DEVICES: DeviceDefinition[] = [
  {
    catalogId: 'INFRA-GATEWAY-KNX',
    name: 'KNX网关',
    description: 'KNX/IP协议网关',
    type: 'gateway',
    subtype: 'knx',
    color: '#94a3b8',
    defaultH: 1.8,
    size: [0.09, 0.06, 0.072],
    subsystem: 'architecture',
    mountType: 'din_rail',
    price: 3500,
  },
  {
    catalogId: 'INFRA-SMART-HOST',
    name: '智能主机',
    description: '智能家居控制中心',
    type: 'host',
    subtype: 'smart',
    color: '#455A64',
    defaultH: 1.8,
    size: [0.3, 0.1, 0.4],
    subsystem: 'architecture',
    mountType: 'wall',
    price: 8000,
  },
]
