/**
 * 产品元数据
 *
 * PRODUCT_META_OVERRIDES — 人工录入的完整 SmartProduct 规格
 * deriveProductMeta      — 从 DeviceDefinition 自动推导基础 SmartProduct
 *
 * 用于现有设备目录的渐进式迁移：
 * - 若 override 存在，直接返回
 * - 否则从 DeviceDefinition 字段推导一个基础版本
 */

import type { Subsystem } from '@pascal-app/core'
import type { SmartProduct } from '../meta'
import type { DeviceDefinition } from './types'

export const PRODUCT_META_OVERRIDES: Record<string, SmartProduct> = {
  'INFRA-GATEWAY-KNX': {
    id: 'INFRA-GATEWAY-KNX',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Gateway-KNX',
      name_zh: 'KNX网关',
      name_en: 'KNX Gateway',
      category: 'gateway',
      subcategory: 'gateway_knx',
    },
    physical: {
      dimensions_mm: { w: 90, h: 60, d: 72 },
      mount_type: 'din_rail',
      mount_face: 'front',
      color_options: ['white', 'gray'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 6,
      max_load_w: null,
    },
    protocol: {
      primary: 'knx',
      supported: ['knx', 'ip'],
      gateway_required: false,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: ['bus_health'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 3500,
      price_tier: 'premium',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [90, 60, 72] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'INFRA-SMART-HOST': {
    id: 'INFRA-SMART-HOST',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Smart-Host',
      name_zh: '智能主机',
      name_en: 'Smart Host',
      category: 'gateway',
      subcategory: 'smart_host',
    },
    physical: {
      dimensions_mm: { w: 300, h: 100, d: 400 },
      mount_type: 'wall',
      mount_face: 'back',
      color_options: ['black'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 18,
      max_load_w: null,
    },
    protocol: {
      primary: 'matter',
      supported: ['matter', 'wifi', 'zigbee', 'knx'],
      gateway_required: false,
      compatible_gateways: ['INFRA-GATEWAY-KNX'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 8000,
      price_tier: 'luxury',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [300, 100, 400] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'SECURITY-CAMERA-DOME': {
    id: 'SECURITY-CAMERA-DOME',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Cam-Dome-01',
      name_zh: '半球摄像头',
      name_en: 'Dome Camera',
      category: 'security',
      subcategory: 'camera_dome',
    },
    physical: {
      dimensions_mm: { w: 120, h: 80, d: 120 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'poe',
      voltage: '48V PoE',
      power_consumption_w: 7,
      max_load_w: null,
    },
    protocol: {
      primary: 'wifi',
      supported: ['wifi', 'rtsp', 'onvif'],
      gateway_required: false,
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 0,
      sensors: ['motion', 'luminance'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 1500,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'sphere', dimensions: [120, 80, 120] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-SWITCH-1KEY': {
    id: 'PANEL-SWITCH-1KEY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-1Key',
      name_zh: '单路开关',
      name_en: '1-Gang Smart Switch',
      category: 'control_panel',
      subcategory: 'mechanical_switch',
    },
    physical: {
      dimensions_mm: { w: 86, h: 8, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black', 'champagne'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 1.5,
      max_load_w: 800,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 1,
      sensors: [],
      voice_control: false,
    },
    commercial: {
      price_rmb: 380,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 8, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-SWITCH-2KEY': {
    id: 'PANEL-SWITCH-2KEY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-2Key',
      name_zh: '双路开关',
      name_en: '2-Gang Smart Switch',
      category: 'control_panel',
      subcategory: 'mechanical_switch',
    },
    physical: {
      dimensions_mm: { w: 86, h: 8, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black', 'champagne'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 1.8,
      max_load_w: 1200,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 2,
      sensors: [],
      voice_control: false,
    },
    commercial: {
      price_rmb: 480,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 8, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-SWITCH-3KEY': {
    id: 'PANEL-SWITCH-3KEY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-3Key',
      name_zh: '三路开关',
      name_en: '3-Gang Smart Switch',
      category: 'control_panel',
      subcategory: 'mechanical_switch',
    },
    physical: {
      dimensions_mm: { w: 86, h: 8, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black', 'champagne'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 2.1,
      max_load_w: 1800,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 3,
      sensors: [],
      voice_control: false,
    },
    commercial: {
      price_rmb: 580,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 8, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'SECURITY-CAMERA-BULLET': {
    id: 'SECURITY-CAMERA-BULLET',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Cam-Bullet-01',
      name_zh: '枪机摄像头',
      name_en: 'Bullet Camera',
      category: 'security',
      subcategory: 'camera_bullet',
    },
    physical: {
      dimensions_mm: { w: 160, h: 80, d: 80 },
      mount_type: 'wall',
      mount_face: 'back',
      color_options: ['white', 'black'],
    },
    electrical: {
      power_source: 'poe',
      voltage: '48V PoE',
      power_consumption_w: 8,
      max_load_w: null,
    },
    protocol: {
      primary: 'wifi',
      supported: ['wifi', 'rtsp', 'onvif'],
      gateway_required: false,
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 0,
      sensors: ['motion', 'infrared'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 1680,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [160, 80, 80] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'NETWORK-AP-CEILING': {
    id: 'NETWORK-AP-CEILING',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'AP-Ceiling-01',
      name_zh: '吸顶AP',
      name_en: 'Ceiling Access Point',
      category: 'network',
      subcategory: 'ap_ceiling',
    },
    physical: {
      dimensions_mm: { w: 200, h: 40, d: 200 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'poe',
      voltage: '48V PoE',
      power_consumption_w: 10,
      max_load_w: null,
    },
    protocol: {
      primary: 'wifi',
      supported: ['wifi', 'ethernet'],
      gateway_required: false,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 0,
      sensors: ['signal_strength'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 1200,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [200, 40, 200] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'NETWORK-AP-WALL': {
    id: 'NETWORK-AP-WALL',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'AP-Wall-86',
      name_zh: '面板AP',
      name_en: 'Wall Access Point',
      category: 'network',
      subcategory: 'ap_wall',
    },
    physical: {
      dimensions_mm: { w: 86, h: 30, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'poe',
      voltage: '48V PoE',
      power_consumption_w: 7,
      max_load_w: null,
    },
    protocol: {
      primary: 'wifi',
      supported: ['wifi', 'ethernet'],
      gateway_required: false,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: false,
      has_screen: false,
      buttons: 0,
      sensors: ['signal_strength'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 800,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 30, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'LIGHT-DOWNLIGHT': {
    id: 'LIGHT-DOWNLIGHT',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Light-Downlight-01',
      name_zh: '智能筒灯',
      name_en: 'Smart Downlight',
      category: 'lighting',
      subcategory: 'downlight',
    },
    physical: {
      dimensions_mm: { w: 85, h: 55, d: 85 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white', 'black'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 9,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'matter'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 680,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [85, 55, 85] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'LIGHT-STRIP': {
    id: 'LIGHT-STRIP',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Light-Strip-01',
      name_zh: 'LED灯带',
      name_en: 'LED Strip',
      category: 'lighting',
      subcategory: 'strip',
    },
    physical: {
      dimensions_mm: { w: 500, h: 5, d: 10 },
      mount_type: 'hidden',
      mount_face: 'top',
      color_options: ['warm_white', 'rgbw'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '24V DC',
      power_consumption_w: 12,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'matter'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 280,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [500, 5, 10] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'LIGHT-PENDANT': {
    id: 'LIGHT-PENDANT',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Light-Pendant-01',
      name_zh: '吊灯',
      name_en: 'Pendant Light',
      category: 'lighting',
      subcategory: 'pendant',
    },
    physical: {
      dimensions_mm: { w: 400, h: 1200, d: 400 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['black', 'white', 'gold'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 24,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'matter'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 1880,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [400, 1200, 400] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'LIGHT-WALL': {
    id: 'LIGHT-WALL',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Light-Wall-01',
      name_zh: '壁灯',
      name_en: 'Wall Light',
      category: 'lighting',
      subcategory: 'wall_light',
    },
    physical: {
      dimensions_mm: { w: 120, h: 280, d: 120 },
      mount_type: 'wall',
      mount_face: 'back',
      color_options: ['white', 'black', 'champagne'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 12,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'matter'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 760,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [120, 280, 120] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-DIMMER-KNOB': {
    id: 'PANEL-DIMMER-KNOB',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-Dimmer-Knob',
      name_zh: '旋钮调光面板',
      name_en: 'Rotary Dimmer Panel',
      category: 'control_panel',
      subcategory: 'dimmer',
    },
    physical: {
      dimensions_mm: { w: 86, h: 12, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black', 'champagne'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 1.8,
      max_load_w: 500,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 1,
      sensors: [],
      voice_control: true,
    },
    commercial: {
      price_rmb: 680,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [86, 12, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-SCENE-4KEY': {
    id: 'PANEL-SCENE-4KEY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-Scene-4Key',
      name_zh: '四键场景面板',
      name_en: '4-Key Scene Panel',
      category: 'control_panel',
      subcategory: 'touch_panel_no_screen',
    },
    physical: {
      dimensions_mm: { w: 86, h: 10, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black'],
    },
    electrical: {
      power_source: 'bus_powered',
      voltage: 'KNX 30V DC',
      power_consumption_w: 1.2,
      max_load_w: null,
    },
    protocol: {
      primary: 'knx',
      supported: ['knx'],
      gateway_required: true,
      compatible_gateways: ['INFRA-GATEWAY-KNX', 'INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 4,
      sensors: [],
      voice_control: false,
    },
    commercial: {
      price_rmb: 980,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 10, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'PANEL-SCENE-6KEY': {
    id: 'PANEL-SCENE-6KEY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Panel-Scene-6Key',
      name_zh: '六键场景面板',
      name_en: '6-Key Scene Panel',
      category: 'control_panel',
      subcategory: 'touch_panel_no_screen',
    },
    physical: {
      dimensions_mm: { w: 86, h: 10, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black'],
    },
    electrical: {
      power_source: 'bus_powered',
      voltage: 'KNX 30V DC',
      power_consumption_w: 1.4,
      max_load_w: null,
    },
    protocol: {
      primary: 'knx',
      supported: ['knx'],
      gateway_required: true,
      compatible_gateways: ['INFRA-GATEWAY-KNX', 'INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 6,
      sensors: [],
      voice_control: false,
    },
    commercial: {
      price_rmb: 1280,
      price_tier: 'premium',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 10, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'HVAC-THERMOSTAT': {
    id: 'HVAC-THERMOSTAT',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'HVAC-Thermostat-01',
      name_zh: '温控器',
      name_en: 'Thermostat',
      category: 'hvac',
      subcategory: 'thermostat',
    },
    physical: {
      dimensions_mm: { w: 86, h: 15, d: 86 },
      mount_type: 'wall_switch',
      mount_face: 'front',
      color_options: ['white', 'black'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '24V DC',
      power_consumption_w: 3,
      max_load_w: null,
    },
    protocol: {
      primary: 'knx',
      supported: ['knx', 'modbus'],
      gateway_required: true,
      compatible_gateways: ['INFRA-GATEWAY-KNX', 'INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: true,
      screen_type: 'color_touch',
      buttons: 2,
      sensors: ['temperature', 'humidity'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 1680,
      price_tier: 'premium',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [86, 15, 86] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'HVAC-VENT-4WAY': {
    id: 'HVAC-VENT-4WAY',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'HVAC-Vent-4Way',
      name_zh: '四向风口',
      name_en: '4-Way Vent',
      category: 'hvac',
      subcategory: 'vent',
    },
    physical: {
      dimensions_mm: { w: 600, h: 60, d: 600 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '24V DC',
      power_consumption_w: 6,
      max_load_w: null,
    },
    protocol: {
      primary: 'modbus',
      supported: ['modbus', 'knx'],
      gateway_required: true,
      compatible_gateways: ['INFRA-GATEWAY-KNX', 'INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: ['airflow'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 980,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2024,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [600, 60, 600] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'CURTAIN-TRACK-MOTOR': {
    id: 'CURTAIN-TRACK-MOTOR',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Curtain-Track-Motor',
      name_zh: '窗帘轨道电机',
      name_en: 'Curtain Track Motor',
      category: 'curtain',
      subcategory: 'track_motor',
    },
    physical: {
      dimensions_mm: { w: 70, h: 300, d: 70 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 45,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'matter'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 1,
      sensors: ['position_feedback'],
      voice_control: true,
    },
    commercial: {
      price_rmb: 1480,
      price_tier: 'mid',
      lifecycle_status: 'active',
      release_year: 2024,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [70, 300, 70] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'SECURITY-DOOR-LOCK': {
    id: 'SECURITY-DOOR-LOCK',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Door-Lock-01',
      name_zh: '智能门锁',
      name_en: 'Smart Door Lock',
      category: 'security',
      subcategory: 'door_lock',
    },
    physical: {
      dimensions_mm: { w: 80, h: 320, d: 35 },
      mount_type: 'door',
      mount_face: 'front',
      color_options: ['black', 'gray'],
    },
    electrical: {
      power_source: 'battery',
      voltage: '7.4V DC',
      power_consumption_w: 2.5,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee', 'bluetooth'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 12,
      sensors: ['door_state', 'tamper'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 2299,
      price_tier: 'premium',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'box', dimensions: [80, 320, 35] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'SECURITY-PIR': {
    id: 'SECURITY-PIR',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'PIR-Sensor-01',
      name_zh: '人体传感器',
      name_en: 'PIR Sensor',
      category: 'sensor',
      subcategory: 'pir',
    },
    physical: {
      dimensions_mm: { w: 58, h: 58, d: 58 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'battery',
      voltage: '3V DC',
      power_consumption_w: 0.2,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: ['motion', 'luminance'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 199,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2024,
    },
    assets: {
      fallback_geometry: { type: 'sphere', dimensions: [58, 58, 58] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'SECURITY-SMOKE': {
    id: 'SECURITY-SMOKE',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Smoke-Sensor-01',
      name_zh: '烟雾传感器',
      name_en: 'Smoke Detector',
      category: 'sensor',
      subcategory: 'smoke',
    },
    physical: {
      dimensions_mm: { w: 100, h: 45, d: 100 },
      mount_type: 'ceiling',
      mount_face: 'top',
      color_options: ['white'],
    },
    electrical: {
      power_source: 'battery',
      voltage: '3V DC',
      power_consumption_w: 0.25,
      max_load_w: null,
    },
    protocol: {
      primary: 'zigbee',
      supported: ['zigbee'],
      gateway_required: true,
      compatible_gateways: ['INFRA-SMART-HOST'],
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 1,
      sensors: ['smoke', 'temperature'],
      voice_control: false,
    },
    commercial: {
      price_rmb: 269,
      price_tier: 'budget',
      lifecycle_status: 'active',
      release_year: 2024,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [100, 45, 100] },
    },
    metadata: { source: 'manual', verified: true },
  },
  'AV-SMART-SPEAKER': {
    id: 'AV-SMART-SPEAKER',
    version: '1.0.0',
    identity: {
      brand: 'VilHil',
      model: 'Smart-Speaker-01',
      name_zh: '智能音箱',
      name_en: 'Smart Speaker',
      category: 'audio_video',
      subcategory: 'smart_speaker',
    },
    physical: {
      dimensions_mm: { w: 140, h: 170, d: 140 },
      mount_type: 'floor',
      mount_face: 'bottom',
      color_options: ['black', 'white'],
    },
    electrical: {
      power_source: 'mains_powered',
      voltage: '220V AC',
      power_consumption_w: 15,
      max_load_w: null,
    },
    protocol: {
      primary: 'matter',
      supported: ['matter', 'wifi', 'bluetooth'],
      gateway_required: false,
    },
    capabilities: {
      scenes: true,
      has_screen: false,
      buttons: 0,
      sensors: ['voice_wake'],
      voice_control: true,
    },
    commercial: {
      price_rmb: 1999,
      price_tier: 'premium',
      lifecycle_status: 'active',
      release_year: 2025,
    },
    assets: {
      fallback_geometry: { type: 'cylinder', dimensions: [140, 170, 140] },
    },
    metadata: { source: 'manual', verified: true },
  },
}

export function deriveProductMeta(def: DeviceDefinition): SmartProduct {
  if (def.productMeta) {
    return def.productMeta
  }

  const override = PRODUCT_META_OVERRIDES[def.catalogId]
  if (override) {
    return override
  }

  const [w, h, d] = def.size
  const categoryMap: Record<Subsystem, SmartProduct['identity']['category']> = {
    architecture: 'gateway',
    lighting: 'lighting',
    panel: 'control_panel',
    sensor: 'sensor',
    curtain: 'curtain',
    hvac: 'hvac',
    av: 'audio_video',
    security: 'security',
    network: 'network',
  }

  return {
    id: def.catalogId,
    identity: {
      brand: 'Generic',
      model: def.modelId || def.catalogId,
      name_zh: def.name,
      category: categoryMap[def.subsystem] ?? 'gateway',
      subcategory: (def.subtype as SmartProduct['identity']['subcategory']) ?? 'unknown',
    },
    physical: {
      dimensions_mm: { w: Math.round(w * 1000), h: Math.round(h * 1000), d: Math.round(d * 1000) },
      mount_type: def.mountType,
    },
    commercial: def.price
      ? {
          price_rmb: def.price,
          price_tier: def.price > 2000 ? 'premium' : def.price > 800 ? 'mid' : 'budget',
        }
      : undefined,
    capabilities: {
      has_screen: def.hasScreen ?? false,
      buttons: def.buttonCount,
      scenes: def.controlType === 'scene',
    },
    assets: {
      fallback_geometry: {
        type: 'box',
        dimensions: [Math.round(w * 1000), Math.round(h * 1000), Math.round(d * 1000)],
      },
    },
  }
}
